name: Update Gist

on:
  push:
    branches: main

  schedule:
    - cron: "0 6 * * *"
      
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: npx pnpm i --store=node_modules/.pnpm-store
      - name: Update gist
        run: npm run status
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 46e4a3d0fe69f67d73620eb07a297a29
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
